### ISSUE TITLE
[docs]: new resources for documentation

### ISSUE THREAD

**Issue by PyaePhyoKyaw61194** [mm-ninja-turtles/turtle-express#46] opened 2022-08-20 11:10 UTC
About the documentation( Github wiki for now), I will add 
**03**. router
**04**.path
**04**.handler
 of the framework.

**Comment by wai-lin** [comment] 2022-08-21 14:23
I'm thinking of using [astro](https://astro.build) for creating documentation website in the future.

**Comment by PyaePhyoKyaw61194** [comment] 2022-08-22 02:59
Got it , let me add in wiki first

**Comment by wai-lin** [comment] 2022-08-23 02:35
this is the duplicate of #23.

**Closed by wai-lin** 2022-08-23 02:35 UTC
Labels: type: documentation, priority:normal, task: todo
